<?php
/**
 * Shareable Report View
 * Public report viewing with login requirement
 */

require_once __DIR__ . '/../security.php';

// Must be logged in to view reports
if (!isset($_SESSION['logged_in'])) {
    header('Location: login.php?redirect=' . urlencode($_SERVER['REQUEST_URI']));
    exit;
}

$token = $_GET['token'] ?? '';

if (empty($token)) {
    header('Location: dashboard.php?page=reports');
    exit;
}

// Fetch report
$stmt = $pdo->prepare("
    SELECT r.*, CONCAT(u.first_name, ' ', u.last_name) as generated_by_name
    FROM reports r
    INNER JOIN users u ON r.generated_by = u.id
    WHERE r.share_token = ?
");
$stmt->execute([$token]);
$report = $stmt->fetch();

if (!$report) {
    die('Report not found or link has expired.');
}

$report_type_display = ucwords(str_replace('_', ' ', $report['report_type']));
?>

<style>
    :root {
        --primary: #7000a4;
    }
    .report-view-container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 40px 20px;
    }
    .report-header {
        background: linear-gradient(135deg, var(--primary) 0%, #4a0070 100%);
        border-radius: 12px;
        padding: 40px;
        margin-bottom: 30px;
        color: #fff;
    }
    .report-title {
        font-size: 32px;
        font-weight: 900;
        margin-bottom: 15px;
    }
    .report-meta {
        font-size: 14px;
        opacity: 0.9;
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
        gap: 15px;
    }
    .meta-item {
        display: flex;
        align-items: center;
        gap: 8px;
    }
    .report-content {
        background: #0a0f14;
        border: 1px solid #1e293b;
        border-radius: 12px;
        padding: 40px;
    }
    .report-actions {
        display: flex;
        gap: 15px;
        margin-bottom: 30px;
    }
    .btn {
        padding: 12px 24px;
        border: none;
        border-radius: 6px;
        font-weight: 700;
        font-size: 14px;
        cursor: pointer;
        transition: all 0.2s;
        display: inline-flex;
        align-items: center;
        gap: 8px;
        text-decoration: none;
    }
    .btn-primary {
        background: var(--primary);
        color: #fff;
    }
    .btn-primary:hover {
        background: #5a0085;
    }
    .btn-secondary {
        background: #334155;
        color: #fff;
    }
    .btn-secondary:hover {
        background: #475569;
    }
    iframe {
        width: 100%;
        min-height: 800px;
        border: none;
        border-radius: 8px;
        background: #fff;
    }
</style>

<div class="report-view-container">
    <div class="report-header">
        <div class="report-title">
            <i class="fas fa-file-<?= $report['format'] === 'pdf' ? 'pdf' : 'csv' ?>"></i>
            <?= htmlspecialchars($report_type_display) ?> Report
        </div>
        <div class="report-meta">
            <div class="meta-item">
                <i class="fas fa-user"></i>
                Generated by: <?= htmlspecialchars($report['generated_by_name']) ?>
            </div>
            <div class="meta-item">
                <i class="fas fa-calendar"></i>
                <?= date('F j, Y g:i A', strtotime($report['created_at'])) ?>
            </div>
            <div class="meta-item">
                <i class="fas fa-file"></i>
                Format: <?= strtoupper($report['format']) ?>
            </div>
        </div>
    </div>
    
    <div class="report-actions">
        <?php if ($report['file_path'] && file_exists(__DIR__ . '/../' . $report['file_path'])): ?>
        <a href="<?= htmlspecialchars($report['file_path']) ?>" class="btn btn-primary" download>
            <i class="fas fa-download"></i> Download Report
        </a>
        <?php endif; ?>
        <button class="btn btn-secondary" onclick="window.print()">
            <i class="fas fa-print"></i> Print
        </button>
        <button class="btn btn-secondary" onclick="copyLink()">
            <i class="fas fa-link"></i> Copy Link
        </button>
        <a href="dashboard.php?page=reports" class="btn btn-secondary">
            <i class="fas fa-arrow-left"></i> Back to Reports
        </a>
    </div>
    
    <div class="report-content">
        <?php if ($report['file_path'] && file_exists(__DIR__ . '/../' . $report['file_path'])): ?>
            <?php if ($report['format'] === 'csv'): ?>
                <div style="overflow-x: auto;">
                    <table style="width: 100%; border-collapse: collapse;">
                        <?php
                        $csv_file = fopen(__DIR__ . '/../' . $report['file_path'], 'r');
                        $is_header = true;
                        while (($row = fgetcsv($csv_file)) !== false) {
                            echo '<tr>';
                            foreach ($row as $cell) {
                                $tag = $is_header ? 'th' : 'td';
                                $style = $is_header ? 'background: #7000a4; color: #fff; padding: 12px; text-align: left;' : 'padding: 12px; border-bottom: 1px solid #1e293b;';
                                echo "<$tag style='$style'>" . htmlspecialchars($cell) . "</$tag>";
                            }
                            echo '</tr>';
                            $is_header = false;
                        }
                        fclose($csv_file);
                        ?>
                    </table>
                </div>
            <?php else: ?>
                <iframe src="<?= htmlspecialchars($report['file_path']) ?>"></iframe>
            <?php endif; ?>
        <?php else: ?>
            <p style="text-align: center; color: #64748b; padding: 60px 0;">
                <i class="fas fa-exclamation-triangle" style="font-size: 48px; margin-bottom: 20px; display: block;"></i>
                Report file not found. It may have been moved or deleted.
            </p>
        <?php endif; ?>
    </div>
</div>

<script>
function copyLink() {
    const url = window.location.href;
    navigator.clipboard.writeText(url).then(() => {
        alert('Share link copied to clipboard!');
    });
}
</script>
